# -*- coding: utf-8 -*-
"""placementPredict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RgO_n5rdr3hQ4Vmq5XltV37W98kmyRNx
"""

import numpy as np
import pandas as pd
import pickle
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from mlxtend.plotting import plot_decision_regions
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

df= pd.read_csv('/content/placement.csv')

df = df.iloc[:,1:]
#df

plt.scatter(df['cgpa'], df['iq'], c=df['placement'])

x = df.iloc[:,0:2]
y = df.iloc[:,-1]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.1)

#y_test
#y_train

scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)
#x_test

clf = LogisticRegression()

# model training
clf.fit(x_train, y_train)

#clf.predict(x_test)
y_pred = clf.predict(x_test)

#y_test

accuracy_score(y_test, y_pred)

plot_decision_regions(x_train, y_train.values, clf=clf, legend=2)

pickle.dump(clf, open('model.pkl', 'wb'))

